% Function to generate foreground region based on saliency map.
% Input:
%     - img: Original image.
%     - saliency_map: Saliency map of the image.
% Output:
%     - binary_map: A binary map to distinct foreground from background,
%           where foreground is 1 and background is 0.
% Writen by chenzy.

function binary_map = generateForeground(img, saliency_map)
    % Binary process with threshold generated by Otsu's method.
    binary_map = im2bw(saliency_map, multithresh(saliency_map));
    if exist('show_foreground_from_image', 'var') == 1
        r_channel = img(:,:,1);
        g_channel = img(:,:,2);
        b_channel = img(:,:,3);
        r_channel(saliency_map == 1) = 255;
        g_channel(saliency_map == 1) = 0;
        b_channel(saliency_map == 1) = 0;
        img_copy = A;
        img_copy(:,:,1) = r_channel;
        img_copy(:,:,2) = g_channel;
        img_copy(:,:,3) = b_channel;
        imshow(img_copy);
    end
end